import "./globals.css";
import { Poppins as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

const fontSans = FontSans({ subsets: ["latin"] });

export const metadata = {
  title: "Best Trip",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen flex flex-col overflow-hidden bg-white antialiased",
          fontSans.className
        )}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
